### Create a new microblogging post
POST http://localhost:8080/api/v1/microblogging
Content-Type: application/json

{
  "userId": "1",
  "content": "This is a new microblogging post"
}

### Get all microblogging posts
GET http://localhost:8080/api/v1/microblogging

### Update a microblogging post
PUT http://localhost:8080/api/v1/microblogging
Content-Type: application/json

{
  "userId": "1",
  "microblogId": "1",
  "content": "This is an updated microblogging post"
}